name: Sync Detection Rules

on:
  push:
    branches:
      - main

jobs:
  sync:
    runs-on: ubuntu-latest

    steps:
      - name: Check out repository
        uses: actions/checkout@v2

      - name: Sync changes
        uses: repo-sync/github-sync@v2
        with:
          source_repo: 0x0Faisal/test-rules
          source_branch: main
          destination_branch: main
